eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  typeAliasesPackage: com.example.userservice.**.entity
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8762
spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
